services:
  neodash:
    image: ghcr.io/neocortex3/neodash:latest
    container_name: neodash
    ports:
      - "9020:3000"
    volumes:
      - data:/app/data #einstellungen
      - uploads:/app/public/uploads #uploads hintergrund, icons
    restart: unless-stopped

volumes:
  data:
  uploads:
